### Add a report
POST  http://localhost:3000/reports
Content-Type: application/json

{
  "make":"mazda",
  "model":"gt",
  "year": 1999,
  "mileage":4999,
  "lng":100,
  "lat":290,
  "price":12399
}

### Approve/Unapprove an existing report
PATCH http://localhost:3000/reports/1
Content-Type: application/json

{
  "approved": false
}

### Get an estimate

GET  http://localhost:3000/reports?make=ford&model=gt&lng=90&lat=90&mileage=20&year=2002