### Add a report
POST  http://localhost:3000/reports
Content-Type: application/json

{
  "make":"toyota",
  "model":"altis",
  "year": 2002,
  "mileage":20,
  "lng":0,
  "lat":0,
  "price":599
}

### Approve/Unapprove an existing report
PATCH http://localhost:3000/reports/1
Content-Type: application/json

{
  "approved": false
}

### Get an estimate

GET  http://localhost:3000/reports?make=toyota&model=altis&lng=0&lat=0&mileage=20&year=2002