### Create a new user

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test+123@example.com",
  "password" :"12345678"
}

### Sign in
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "test+123@example.com",
  "password" :"12345678"
}

### current signed in user
GET http://localhost:3000/auth/whoami

### sign out
POST http://localhost:3000/auth/signout